Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/3d/binding_expt.py", line 257, in <module>
    main(**pars)
  File "src/3d/binding_expt.py", line 151, in main
    result = integrate_motion(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 876, in integrate_motion
    res = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  [Previous line repeated 21 more times]
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 330, in time_step
    raise OverflowError()
OverflowError
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/3d/binding_expt.py", line 257, in <module>
    main(**pars)
  File "src/3d/binding_expt.py", line 151, in main
    result = integrate_motion(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 876, in integrate_motion
    res = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  [Previous line repeated 21 more times]
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 330, in time_step
    raise OverflowError()
OverflowError
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/3d/binding_expt.py", line 257, in <module>
    main(**pars)
  File "src/3d/binding_expt.py", line 151, in main
    result = integrate_motion(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 876, in integrate_motion
    res = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  [Previous line repeated 21 more times]
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 330, in time_step
    raise OverflowError()
OverflowError
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/3d/binding_expt.py", line 257, in <module>
    main(**pars)
  File "src/3d/binding_expt.py", line 151, in main
    result = integrate_motion(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 876, in integrate_motion
    res = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  [Previous line repeated 21 more times]
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 330, in time_step
    raise OverflowError()
OverflowError
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/3d/binding_expt.py", line 257, in <module>
    main(**pars)
  File "src/3d/binding_expt.py", line 151, in main
    result = integrate_motion(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 876, in integrate_motion
    res = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  [Previous line repeated 21 more times]
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 330, in time_step
    raise OverflowError()
OverflowError
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/3d/binding_expt.py", line 257, in <module>
    main(**pars)
  File "src/3d/binding_expt.py", line 151, in main
    result = integrate_motion(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 876, in integrate_motion
    res = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  [Previous line repeated 21 more times]
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 330, in time_step
    raise OverflowError()
OverflowError
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/3d/binding_expt.py", line 257, in <module>
    main(**pars)
  File "src/3d/binding_expt.py", line 151, in main
    result = integrate_motion(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 876, in integrate_motion
    res = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  [Previous line repeated 21 more times]
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 330, in time_step
    raise OverflowError()
OverflowError
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/3d/binding_expt.py", line 257, in <module>
    main(**pars)
  File "src/3d/binding_expt.py", line 151, in main
    result = integrate_motion(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 876, in integrate_motion
    res = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  [Previous line repeated 21 more times]
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 330, in time_step
    raise OverflowError()
OverflowError
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/3d/binding_expt.py", line 257, in <module>
    main(**pars)
  File "src/3d/binding_expt.py", line 151, in main
    result = integrate_motion(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 876, in integrate_motion
    res = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  [Previous line repeated 21 more times]
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 330, in time_step
    raise OverflowError()
OverflowError
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 437, in time_step
    half_step2 = evaluate_motion_equations(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 204, in evaluate_motion_equations
    assert (domain == 'free' or valid_orientation(n_nodes=48, e_m=e_m,
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 469, in time_step
    raise AssertionError('next step will not be valid')
AssertionError: next step will not be valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/3d/binding_expt.py", line 257, in <module>
    main(**pars)
  File "src/3d/binding_expt.py", line 151, in main
    result = integrate_motion(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 876, in integrate_motion
    res = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 485, in time_step
    result1 = time_step(
  [Previous line repeated 21 more times]
  File "/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/motion_integration.py", line 330, in time_step
    raise OverflowError()
OverflowError
/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/src/3d/resistance_matrix_test.py:56: LinAlgWarning: Ill-conditioned matrix (rcond=1.18127e-17): result may not be accurate.
  intermediate_solve = solve(
slurmstepd: error: *** JOB 2280134 ON notch081 CANCELLED AT 2021-03-20T20:57:29 DUE TO TIME LIMIT ***
